In [1]:
##setup

import glob
import os
import pandas as pd

processed_dir = '/Users/audriswong/data-portfolio/projects/seattle-checkouts/data/processed'

## determine uniqueness of physical books dataset

### is checkout data unique at monthly grain per title?  ISBN?

In [2]:
#test uniqueness - is each book isbn unique per month?
physical_checkouts = pd.read_parquet(f'{processed_dir}/physical_checkouts.parquet')

# Count how many rows exist per title per month per year
isbn_counts = physical_checkouts[
    (physical_checkouts['materialtype'] == 'BOOK') &
    (physical_checkouts['checkoutyear'] == 2024) &
    (physical_checkouts['checkoutmonth'] == 12)
].groupby(['isbn', 'checkoutyear', 'checkoutmonth']).size().reset_index(name='row_count')

# If max row_count = 1, titles are unique per month/year
print(f"Max rows per ISBN per month: {isbn_counts['row_count'].max()}")
print(f"ISBNs with duplicates: {(isbn_counts['row_count'] > 1).sum()}")
print(f"Total unique ISBNs: {len(isbn_counts):,}")

Max rows per ISBN per month: 5
ISBNs with duplicates: 22077
Total unique ISBNs: 59,189

In [3]:
#test uniqueness - is each book title unique per month?
physical_checkouts = pd.read_parquet(f'{processed_dir}/physical_checkouts.parquet')

# Count how many rows exist per title per month per year
title_counts = physical_checkouts[
    (physical_checkouts['materialtype'] == 'BOOK') &
    (physical_checkouts['checkoutyear'] == 2024) &
    (physical_checkouts['checkoutmonth'] == 12)
].groupby(['title', 'checkoutyear', 'checkoutmonth']).size().reset_index(name='row_count')

# If max row_count = 1, titles are unique per month/year
print(f"Max rows per title per month: {title_counts['row_count'].max()}")
print(f"Titles with duplicates: {(title_counts['row_count'] > 1).sum()}")
print(f"Total unique titles: {len(title_counts):,}")

Max rows per title per month: 6
Titles with duplicates: 22459
Total unique titles: 59,286

In [4]:
# Show sample duplicate ISBNs
duplicate_isbns = isbn_counts[isbn_counts['row_count'] > 1]['isbn'].head(5).tolist()

# Show the actual rows for those ISBNs
physical_checkouts[
    (physical_checkouts['materialtype'] == 'BOOK') &
    (physical_checkouts['checkoutyear'] == 2024) &
    (physical_checkouts['checkoutmonth'] == 12) &
    (physical_checkouts['isbn'].isin(duplicate_isbns))
].sort_values('isbn')

,usageclass,checkouttype,materialtype,checkoutyear,checkoutmonth,checkouts,title,creator,subjects,publisher,publicationyear,isbn,materialtype_upper,title_clean,creator_clean,title_book_clean,work_key,month_date
4450316,Physical,Horizon,BOOK,2024,12,10,Bog Myrtle / Sid Sharp.,"Sharp, Sid","Siblings Comic books strips etc, Spiders Comic...","Annick Press,",2024.,", 1773218921, 1773218948, 9781773218922, 97817...",BOOK,BOG MYRTLE / SID SHARP.,"SHARP, SID",BOG MYRTLE,"BOG MYRTLE / SID SHARP.||SHARP, SID",2024-12-01
8784228,Physical,Horizon,BOOK,2024,12,10,Bog Myrtle / Sid Sharp.,"Sharp, Sid","Siblings Comic books strips etc, Spiders Comic...","Annick Press,",2024.,", 1773218921, 1773218948, 9781773218922, 97817...",BOOK,BOG MYRTLE / SID SHARP.,"SHARP, SID",BOG MYRTLE,"BOG MYRTLE / SID SHARP.||SHARP, SID",2024-12-01
161357,Physical,Horizon,BOOK,2024,12,2,Spring story / Jill Barklem.,"Barklem, Jill","Mice Juvenile fiction, Birthdays Juvenile fict...","HarperCollins Children's Books,",2020.,"0001839225, 0008241171, 9780001839229, 9780008...",BOOK,SPRING STORY / JILL BARKLEM.,"BARKLEM, JILL",SPRING STORY,"SPRING STORY / JILL BARKLEM.||BARKLEM, JILL",2024-12-01
3038426,Physical,Horizon,BOOK,2024,12,2,Spring story / Jill Barklem.,"Barklem, Jill","Mice Juvenile fiction, Birthdays Juvenile fict...","HarperCollins Children's Books,",2020.,"0001839225, 0008241171, 9780001839229, 9780008...",BOOK,SPRING STORY / JILL BARKLEM.,"BARKLEM, JILL",SPRING STORY,"SPRING STORY / JILL BARKLEM.||BARKLEM, JILL",2024-12-01
6983022,Physical,Horizon,BOOK,2024,12,1,Junior : Griffey on Griffey / written by Ken G...,"Griffey, Ken, Jr.","Griffey Ken Jr, Seattle Mariners Baseball team...","CollinsPublishers ,",[1997],"0002252198, 0006491545",BOOK,JUNIOR : GRIFFEY ON GRIFFEY / WRITTEN BY KEN G...,"GRIFFEY, KEN, JR.",JUNIOR : GRIFFEY ON GRIFFEY,JUNIOR : GRIFFEY ON GRIFFEY / WRITTEN BY KEN G...,2024-12-01
7133258,Physical,Horizon,BOOK,2024,12,1,Junior : Griffey on Griffey / written by Ken G...,"Griffey, Ken, Jr.","Griffey Ken Jr, Seattle Mariners Baseball team...","CollinsPublishers ,",[1997],"0002252198, 0006491545",BOOK,JUNIOR : GRIFFEY ON GRIFFEY / WRITTEN BY KEN G...,"GRIFFEY, KEN, JR.",JUNIOR : GRIFFEY ON GRIFFEY,JUNIOR : GRIFFEY ON GRIFFEY / WRITTEN BY KEN G...,2024-12-01
12001365,Physical,Horizon,BOOK,2024,12,1,Junior : Griffey on Griffey / written by Ken G...,"Griffey, Ken, Jr.","Griffey Ken Jr, Seattle Mariners Baseball team...","CollinsPublishers ,",[1997],"0002252198, 0006491545",BOOK,JUNIOR : GRIFFEY ON GRIFFEY / WRITTEN BY KEN G...,"GRIFFEY, KEN, JR.",JUNIOR : GRIFFEY ON GRIFFEY,JUNIOR : GRIFFEY ON GRIFFEY / WRITTEN BY KEN G...,2024-12-01
10640948,Physical,Horizon,BOOK,2024,12,8,Mog the forgetful cat / written and illustrate...,"Kerr, Judith",Mog Fictitious character from Kerr Juvenile fi...,"HarperCollins Children's Books,",2013.,"000717134X, 0007211341, 0007526326, 9780007171...",BOOK,MOG THE FORGETFUL CAT / WRITTEN AND ILLUSTRATE...,"KERR, JUDITH",MOG THE FORGETFUL CAT,MOG THE FORGETFUL CAT / WRITTEN AND ILLUSTRATE...,2024-12-01
12138742,Physical,Horizon,BOOK,2024,12,8,Mog the forgetful cat / written and illustrate...,"Kerr, Judith",Mog Fictitious character from Kerr Juvenile fi...,"HarperCollins Children's Books,",2013.,"000717134X, 0007211341, 0007526326, 9780007171...",BOOK,MOG THE FORGETFUL CAT / WRITTEN AND ILLUSTRATE...,"KERR, JUDITH",MOG THE FORGETFUL CAT,MOG THE FORGETFUL CAT / WRITTEN AND ILLUSTRATE...,2024-12-01
5274424,Physical,Horizon,BOOK,2024,12,3,Night of power : the betrayal of the Middle Ea...,"Fisk, Robert","Middle East History 21st century, Middle East ...","4th Estate,",2024.,"0007255489, 0007350619, 9780007255481, 9780007...",BOOK,NIGHT OF POWER : THE BETRAYAL OF THE MIDDLE EA...,"FISK, ROBERT",NIGHT OF POWER : THE BETRAYAL OF THE MIDDLE EAST,NIGHT OF POWER : THE BETRAYAL OF THE MIDDLE EA...,2024-12-01
11285307,Physical,Horizon,BOOK,2024,12,3,Night of power : the betrayal of the Middle Ea...,"Fisk, Robert","Middle East History 21st century, Middle East ...","4th Estate,",2024.,"0007255489, 0007350619, 9780007255481, 9780007...",BOOK,NIGHT OF POWER : THE BETRAYAL OF THE MIDDLE EA...,"FISK, ROBERT",NIGHT OF POWER : THE BETRAYAL OF THE MIDDLE EAST,NIGHT OF POWER : THE BETRAYAL OF THE MIDDLE EA...,2024-12-01

In [5]:
# Show sample duplicate titles
duplicate_titles = title_counts[title_counts['row_count'] > 1]['title'].head(5).tolist()

# Show the actual rows for those titles
physical_checkouts[
    (physical_checkouts['materialtype'] == 'BOOK') &
    (physical_checkouts['checkoutyear'] == 2024) &
    (physical_checkouts['checkoutmonth'] == 12) &
    (physical_checkouts['title'].isin(duplicate_titles))
].sort_values('title')

,usageclass,checkouttype,materialtype,checkoutyear,checkoutmonth,checkouts,title,creator,subjects,publisher,publicationyear,isbn,materialtype_upper,title_clean,creator_clean,title_book_clean,work_key,month_date
1044909,Physical,Horizon,BOOK,2024,12,2,!Vamos a celebrar! : fechas especiales en el m...,"DePalma, Kate","Holidays Juvenile literature, Festivals Juveni...","Barefoot Books,",2024.,9798888592090,BOOK,!VAMOS A CELEBRAR! : FECHAS ESPECIALES EN EL M...,"DEPALMA, KATE",!VAMOS A CELEBRAR! : FECHAS ESPECIALES EN EL M...,!VAMOS A CELEBRAR! : FECHAS ESPECIALES EN EL M...,2024-12-01
1619132,Physical,Horizon,BOOK,2024,12,2,!Vamos a celebrar! : fechas especiales en el m...,"DePalma, Kate","Holidays Juvenile literature, Festivals Juveni...","Barefoot Books,",2024.,9798888592090,BOOK,!VAMOS A CELEBRAR! : FECHAS ESPECIALES EN EL M...,"DEPALMA, KATE",!VAMOS A CELEBRAR! : FECHAS ESPECIALES EN EL M...,!VAMOS A CELEBRAR! : FECHAS ESPECIALES EN EL M...,2024-12-01
340564,Physical,Horizon,BOOK,2024,12,2,"""All the real Indians died off"" : and 20 other...","Dunbar-Ortiz, Roxanne, 1938-",Indians of North America Historiography,"Beacon Press,",2016.,"0807062650, 9780807062654",BOOK,"""ALL THE REAL INDIANS DIED OFF"" : AND 20 OTHER...","DUNBAR-ORTIZ, ROXANNE","""ALL THE REAL INDIANS DIED OFF"" : AND 20 OTHER...","""ALL THE REAL INDIANS DIED OFF"" : AND 20 OTHER...",2024-12-01
5271809,Physical,Horizon,BOOK,2024,12,2,"""All the real Indians died off"" : and 20 other...","Dunbar-Ortiz, Roxanne, 1938-",Indians of North America Historiography,"Beacon Press,",2016.,"0807062650, 9780807062654",BOOK,"""ALL THE REAL INDIANS DIED OFF"" : AND 20 OTHER...","DUNBAR-ORTIZ, ROXANNE","""ALL THE REAL INDIANS DIED OFF"" : AND 20 OTHER...","""ALL THE REAL INDIANS DIED OFF"" : AND 20 OTHER...",2024-12-01
1045180,Physical,Horizon,BOOK,2024,12,1,"""Better living"" : advertising, media and the n...","Bird, William L., Jr.","Advertising United States History, Public rela...","Northwestern University Press,",1999.,"0810115859, 0810115867",BOOK,"""BETTER LIVING"" : ADVERTISING, MEDIA AND THE N...","BIRD, WILLIAM L., JR.","""BETTER LIVING"" : ADVERTISING, MEDIA AND THE N...","""BETTER LIVING"" : ADVERTISING, MEDIA AND THE N...",2024-12-01
1619403,Physical,Horizon,BOOK,2024,12,1,"""Better living"" : advertising, media and the n...","Bird, William L., Jr.","Advertising United States History, Public rela...","Northwestern University Press,",1999.,"0810115859, 0810115867",BOOK,"""BETTER LIVING"" : ADVERTISING, MEDIA AND THE N...","BIRD, WILLIAM L., JR.","""BETTER LIVING"" : ADVERTISING, MEDIA AND THE N...","""BETTER LIVING"" : ADVERTISING, MEDIA AND THE N...",2024-12-01
341642,Physical,Horizon,BOOK,2024,12,1,"""D"" is for deadbeat / Sue Grafton.","Grafton, Sue",Millhone Kinsey Fictitious character 1950 Fict...,"H. Holt,",[1987],"0805002480, 9780805002485",BOOK,"""D"" IS FOR DEADBEAT / SUE GRAFTON.","GRAFTON, SUE","""D"" IS FOR DEADBEAT","""D"" IS FOR DEADBEAT / SUE GRAFTON.||GRAFTON, SUE",2024-12-01
5272887,Physical,Horizon,BOOK,2024,12,1,"""D"" is for deadbeat / Sue Grafton.","Grafton, Sue",Millhone Kinsey Fictitious character 1950 Fict...,"H. Holt,",[1987],"0805002480, 9780805002485",BOOK,"""D"" IS FOR DEADBEAT / SUE GRAFTON.","GRAFTON, SUE","""D"" IS FOR DEADBEAT","""D"" IS FOR DEADBEAT / SUE GRAFTON.||GRAFTON, SUE",2024-12-01
1532500,Physical,Horizon,BOOK,2024,12,2,"""I'm not Santa!"" / Jonathan Allen.","Allen, Jonathan, 1957-","Mistaken identity Juvenile fiction, Santa Clau...","Hyperion Books for Children,",2008.,"1423113004, 9781423113003",BOOK,"""I'M NOT SANTA!"" / JONATHAN ALLEN.","ALLEN, JONATHAN","""I'M NOT SANTA!""","""I'M NOT SANTA!"" / JONATHAN ALLEN.||ALLEN, JON...",2024-12-01
3302874,Physical,Horizon,BOOK,2024,12,2,"""I'm not Santa!"" / Jonathan Allen.","Allen, Jonathan, 1957-","Mistaken identity Juvenile fiction, Santa Clau...","Hyperion Books for Children,",2008.,"1423113004, 9781423113003",BOOK,"""I'M NOT SANTA!"" / JONATHAN ALLEN.","ALLEN, JONATHAN","""I'M NOT SANTA!""","""I'M NOT SANTA!"" / JONATHAN ALLEN.||ALLEN, JON...",2024-12-01

In [6]:
# Find titles that appear multiple times but have different ISBNs
isbn_check = physical_checkouts[
    (physical_checkouts['materialtype'] == 'BOOK') &
    (physical_checkouts['checkoutyear'] == 2024) &
    (physical_checkouts['checkoutmonth'] == 12)
].groupby('title').agg(
    row_count=('title', 'count'),
    unique_isbns=('isbn', 'nunique')
).reset_index()

# Duplicate titles with different ISBNs
different_isbns = isbn_check[
    (isbn_check['row_count'] > 1) &
    (isbn_check['unique_isbns'] > 1)
]

print(f"Titles with duplicates and different ISBNs: {len(different_isbns):,}")

# Show sample rows from source data for these titles
sample_titles = different_isbns['title'].head(3).tolist()
physical_checkouts[
    (physical_checkouts['materialtype'] == 'BOOK') &
    (physical_checkouts['checkoutyear'] == 2024) &
    (physical_checkouts['checkoutmonth'] == 12) &
    (physical_checkouts['title'].isin(sample_titles))
].sort_values('title')

Titles with duplicates and different ISBNs: 560

,usageclass,checkouttype,materialtype,checkoutyear,checkoutmonth,checkouts,title,creator,subjects,publisher,publicationyear,isbn,materialtype_upper,title_clean,creator_clean,title_book_clean,work_key,month_date
8177376,Physical,Horizon,BOOK,2024,12,1,'Twas the bite before Christmas / David Rosenf...,"Rosenfelt, David","Carpenter Andy Fictitious character Fiction, D...","Thorndike Press, a part of Gale, a Cengage Com...",2023.,9798885794053,BOOK,'TWAS THE BITE BEFORE CHRISTMAS / DAVID ROSENF...,"ROSENFELT, DAVID",'TWAS THE BITE BEFORE CHRISTMAS,'TWAS THE BITE BEFORE CHRISTMAS / DAVID ROSENF...,2024-12-01
9571727,Physical,Horizon,BOOK,2024,12,4,'Twas the bite before Christmas / David Rosenf...,"Rosenfelt, David","Carpenter Andy Fictitious character Fiction, D...","Minotaur Books,",2023.,"1250828848, 9781250828842",BOOK,'TWAS THE BITE BEFORE CHRISTMAS / DAVID ROSENF...,"ROSENFELT, DAVID",'TWAS THE BITE BEFORE CHRISTMAS,'TWAS THE BITE BEFORE CHRISTMAS / DAVID ROSENF...,2024-12-01
11788203,Physical,Horizon,BOOK,2024,12,4,'Twas the bite before Christmas / David Rosenf...,"Rosenfelt, David","Carpenter Andy Fictitious character Fiction, D...","Minotaur Books,",2023.,"1250828848, 9781250828842",BOOK,'TWAS THE BITE BEFORE CHRISTMAS / DAVID ROSENF...,"ROSENFELT, DAVID",'TWAS THE BITE BEFORE CHRISTMAS,'TWAS THE BITE BEFORE CHRISTMAS / DAVID ROSENF...,2024-12-01
162212,Physical,Horizon,BOOK,2024,12,1,1st case / James Patterson and Chris Tebbetts.,"Patterson, James, 1947-",United States Federal Bureau of Investigation ...,"Little, Brown and Company,",2020.,"0316418188, 9780316418188",BOOK,1ST CASE / JAMES PATTERSON AND CHRIS TEBBETTS.,"PATTERSON, JAMES",1ST CASE,1ST CASE / JAMES PATTERSON AND CHRIS TEBBETTS....,2024-12-01
3039281,Physical,Horizon,BOOK,2024,12,1,1st case / James Patterson and Chris Tebbetts.,"Patterson, James, 1947-",United States Federal Bureau of Investigation ...,"Little, Brown and Company,",2020.,"0316418188, 9780316418188",BOOK,1ST CASE / JAMES PATTERSON AND CHRIS TEBBETTS.,"PATTERSON, JAMES",1ST CASE,1ST CASE / JAMES PATTERSON AND CHRIS TEBBETTS....,2024-12-01
6984291,Physical,Horizon,BOOK,2024,12,1,1st case / James Patterson and Chris Tebbetts.,"Patterson, James, 1947-",United States Federal Bureau of Investigation ...,"Little, Brown and Company,",2020.,"0316418315, 1648380360, 9780316418317, 9781648...",BOOK,1ST CASE / JAMES PATTERSON AND CHRIS TEBBETTS.,"PATTERSON, JAMES",1ST CASE,1ST CASE / JAMES PATTERSON AND CHRIS TEBBETTS....,2024-12-01
7134527,Physical,Horizon,BOOK,2024,12,1,1st case / James Patterson and Chris Tebbetts.,"Patterson, James, 1947-",United States Federal Bureau of Investigation ...,"Little, Brown and Company,",2020.,"0316418315, 1648380360, 9780316418317, 9781648...",BOOK,1ST CASE / JAMES PATTERSON AND CHRIS TEBBETTS.,"PATTERSON, JAMES",1ST CASE,1ST CASE / JAMES PATTERSON AND CHRIS TEBBETTS....,2024-12-01
1046099,Physical,Horizon,BOOK,2024,12,3,2054 : a novel / Elliot Ackerman and Admiral J...,"Ackerman, Elliot",United States Politics and government 2021 Fic...,"Penguin Press,",2024.,"0593489861, 0593830857, 9780593489864, 9780593...",BOOK,2054 : A NOVEL / ELLIOT ACKERMAN AND ADMIRAL J...,"ACKERMAN, ELLIOT",2054 : A NOVEL,2054 : A NOVEL / ELLIOT ACKERMAN AND ADMIRAL J...,2024-12-01
1047469,Physical,Horizon,BOOK,2024,12,1,2054 : a novel / Elliot Ackerman and Admiral J...,"Ackerman, Elliot","Large type books, United States Politics and g...","Thorndike Press, a part of Gale, a Cengage Com...",2024.,"1420516213, 9781420516210",BOOK,2054 : A NOVEL / ELLIOT ACKERMAN AND ADMIRAL J...,"ACKERMAN, ELLIOT",2054 : A NOVEL,2054 : A NOVEL / ELLIOT ACKERMAN AND ADMIRAL J...,2024-12-01
1620322,Physical,Horizon,BOOK,2024,12,3,2054 : a novel / Elliot Ackerman and Admiral J...,"Ackerman, Elliot",United States Politics and government 2021 Fic...,"Penguin Press,",2024.,"0593489861, 0593830857, 9780593489864, 9780593...",BOOK,2054 : A NOVEL / ELLIOT ACKERMAN AND ADMIRAL J...,"ACKERMAN, ELLIOT",2054 : A NOVEL,2054 : A NOVEL / ELLIOT ACKERMAN AND ADMIRAL J...,2024-12-01

## do the same checks for digital ebooks

In [7]:
#test uniqueness - is each ebook isbn unique per month?
digital_checkouts = pd.read_parquet(f'{processed_dir}/digital_checkouts.parquet')

# Count how many rows exist per title per month per year
digital_isbn_counts = digital_checkouts[
    (digital_checkouts['materialtype'] == 'EBOOK') &
    (digital_checkouts['checkoutyear'] == 2024) &
    (digital_checkouts['checkoutmonth'] == 12)
].groupby(['isbn', 'checkoutyear', 'checkoutmonth']).size().reset_index(name='row_count')

# If max row_count = 1, titles are unique per month/year
print(f"Max rows per ISBN per month: {digital_isbn_counts['row_count'].max()}")
print(f"ISBNs with duplicates: {(digital_isbn_counts['row_count'] > 1).sum()}")
print(f"Total unique ISBNs: {len(digital_isbn_counts):,}")

Max rows per ISBN per month: 4
ISBNs with duplicates: 21133
Total unique ISBNs: 56,791

In [8]:
#test uniqueness - is each ebook title unique per month?
digital_checkouts = pd.read_parquet(f'{processed_dir}/digital_checkouts.parquet')

# Count how many rows exist per title per month per year
digital_title_counts = digital_checkouts[
    (digital_checkouts['materialtype'] == 'EBOOK') &
    (digital_checkouts['checkoutyear'] == 2024) &
    (digital_checkouts['checkoutmonth'] == 12)
].groupby(['title', 'checkoutyear', 'checkoutmonth']).size().reset_index(name='row_count')

# If max row_count = 1, titles are unique per month/year
print(f"Max rows per ISBN per month: {digital_title_counts['row_count'].max()}")
print(f"ISBNs with duplicates: {(digital_title_counts['row_count'] > 1).sum()}")
print(f"Total unique ISBNs: {len(digital_title_counts):,}")

Max rows per ISBN per month: 11
ISBNs with duplicates: 21498
Total unique ISBNs: 56,071

In [9]:
# Show sample duplicate ISBNs
duplicate_digital_isbns = digital_isbn_counts[digital_isbn_counts['row_count'] > 1]['isbn'].head(5).tolist()

# Show the actual rows for those ISBNs
digital_checkouts[
    (digital_checkouts['materialtype'] == 'EBOOK') &
    (digital_checkouts['checkoutyear'] == 2024) &
    (digital_checkouts['checkoutmonth'] == 12) &
    (digital_checkouts['isbn'].isin(duplicate_digital_isbns))
].sort_values('isbn')

,usageclass,checkouttype,materialtype,checkoutyear,checkoutmonth,checkouts,title,creator,subjects,publisher,publicationyear,isbn,materialtype_upper,title_clean,creator_clean,title_book_clean,work_key,month_date
4022438,Digital,OverDrive,EBOOK,2024,12,1,Pride and Prejudice,Jane Austen,"Classic Literature, Fiction",Barnes & Noble World Digital Library,2005,0594081610,EBOOK,PRIDE AND PREJUDICE,JANE AUSTEN,PRIDE AND PREJUDICE,PRIDE AND PREJUDICE||JANE AUSTEN,2024-12-01
7634602,Digital,OverDrive,EBOOK,2024,12,1,Pride and Prejudice,Jane Austen,"Classic Literature, Fiction",Barnes & Noble World Digital Library,2005,0594081610,EBOOK,PRIDE AND PREJUDICE,JANE AUSTEN,PRIDE AND PREJUDICE,PRIDE AND PREJUDICE||JANE AUSTEN,2024-12-01
200805,Digital,OverDrive,EBOOK,2024,12,3,Sense and Sensibility (World Digital Library E...,Jane Austen,"Classic Literature, Fiction",Barnes & Noble World Digital Library,2005,0594082714,EBOOK,SENSE AND SENSIBILITY (WORLD DIGITAL LIBRARY E...,JANE AUSTEN,SENSE AND SENSIBILITY (WORLD DIGITAL LIBRARY E...,SENSE AND SENSIBILITY (WORLD DIGITAL LIBRARY E...,2024-12-01
2805095,Digital,OverDrive,EBOOK,2024,12,3,Sense and Sensibility (World Digital Library E...,Jane Austen,"Classic Literature, Fiction",Barnes & Noble World Digital Library,2005,0594082714,EBOOK,SENSE AND SENSIBILITY (WORLD DIGITAL LIBRARY E...,JANE AUSTEN,SENSE AND SENSIBILITY (WORLD DIGITAL LIBRARY E...,SENSE AND SENSIBILITY (WORLD DIGITAL LIBRARY E...,2024-12-01
3001758,Digital,OverDrive,EBOOK,2024,12,1,Oliver Twist (World Digital Library Edition),Charles Dickens,"Fiction, Literature",Barnes & Noble World Digital Library,2005,059408301X,EBOOK,OLIVER TWIST (WORLD DIGITAL LIBRARY EDITION),CHARLES DICKENS,OLIVER TWIST (WORLD DIGITAL LIBRARY EDITION),OLIVER TWIST (WORLD DIGITAL LIBRARY EDITION)||...,2024-12-01
6719630,Digital,OverDrive,EBOOK,2024,12,1,Oliver Twist (World Digital Library Edition),Charles Dickens,"Fiction, Literature",Barnes & Noble World Digital Library,2005,059408301X,EBOOK,OLIVER TWIST (WORLD DIGITAL LIBRARY EDITION),CHARLES DICKENS,OLIVER TWIST (WORLD DIGITAL LIBRARY EDITION),OLIVER TWIST (WORLD DIGITAL LIBRARY EDITION)||...,2024-12-01
4695366,Digital,OverDrive,EBOOK,2024,12,2,A Little Princess (World Digital Library Edition),Frances Hodgson Burnett,"Juvenile Fiction, Juvenile Literature",Barnes & Noble World Digital Library,2005,0594083567,EBOOK,A LITTLE PRINCESS (WORLD DIGITAL LIBRARY EDITION),FRANCES HODGSON BURNETT,A LITTLE PRINCESS (WORLD DIGITAL LIBRARY EDITION),A LITTLE PRINCESS (WORLD DIGITAL LIBRARY EDITI...,2024-12-01
9860559,Digital,OverDrive,EBOOK,2024,12,2,A Little Princess (World Digital Library Edition),Frances Hodgson Burnett,"Juvenile Fiction, Juvenile Literature",Barnes & Noble World Digital Library,2005,0594083567,EBOOK,A LITTLE PRINCESS (WORLD DIGITAL LIBRARY EDITION),FRANCES HODGSON BURNETT,A LITTLE PRINCESS (WORLD DIGITAL LIBRARY EDITION),A LITTLE PRINCESS (WORLD DIGITAL LIBRARY EDITI...,2024-12-01
3004533,Digital,OverDrive,EBOOK,2024,12,4,A Christmas Carol (World Digital Library Edition),Charles Dickens,"Fiction, Literature",Barnes & Noble World Digital Library,2005,0594083710,EBOOK,A CHRISTMAS CAROL (WORLD DIGITAL LIBRARY EDITION),CHARLES DICKENS,A CHRISTMAS CAROL (WORLD DIGITAL LIBRARY EDITION),A CHRISTMAS CAROL (WORLD DIGITAL LIBRARY EDITI...,2024-12-01
6722405,Digital,OverDrive,EBOOK,2024,12,4,A Christmas Carol (World Digital Library Edition),Charles Dickens,"Fiction, Literature",Barnes & Noble World Digital Library,2005,0594083710,EBOOK,A CHRISTMAS CAROL (WORLD DIGITAL LIBRARY EDITION),CHARLES DICKENS,A CHRISTMAS CAROL (WORLD DIGITAL LIBRARY EDITION),A CHRISTMAS CAROL (WORLD DIGITAL LIBRARY EDITI...,2024-12-01

In [10]:
# Show sample duplicate titles
duplicate_digital_titles = digital_title_counts[digital_title_counts['row_count'] > 1]['title'].head(5).tolist()

# Show the actual rows for those ISBNs
digital_checkouts[
    (digital_checkouts['materialtype'] == 'EBOOK') &
    (digital_checkouts['checkoutyear'] == 2024) &
    (digital_checkouts['checkoutmonth'] == 12) &
    (digital_checkouts['title'].isin(duplicate_digital_titles))
].sort_values('title')

,usageclass,checkouttype,materialtype,checkoutyear,checkoutmonth,checkouts,title,creator,subjects,publisher,publicationyear,isbn,materialtype_upper,title_clean,creator_clean,title_book_clean,work_key,month_date
4024821,Digital,OverDrive,EBOOK,2024,12,1,"""B"" Is for Betsy",Carolyn Haywood,"Juvenile Fiction, Juvenile Literature",HarperCollins Publishers Inc.,2011,9780547671338,EBOOK,"""B"" IS FOR BETSY",CAROLYN HAYWOOD,"""B"" IS FOR BETSY","""B"" IS FOR BETSY||CAROLYN HAYWOOD",2024-12-01
10063161,Digital,OverDrive,EBOOK,2024,12,1,"""B"" Is for Betsy",Carolyn Haywood,"Juvenile Fiction, Juvenile Literature",HarperCollins Publishers Inc.,2011,9780547671338,EBOOK,"""B"" IS FOR BETSY",CAROLYN HAYWOOD,"""B"" IS FOR BETSY","""B"" IS FOR BETSY||CAROLYN HAYWOOD",2024-12-01
9210941,Digital,OverDrive,EBOOK,2024,12,1,"""I Have Nothing to Hide"": And 20 Other Myths A...",Heidi Boghosian,"Politics, Sociology, Nonfiction, Media Studies","Random House, Inc.",2021,9780807061275,EBOOK,"""I HAVE NOTHING TO HIDE"": AND 20 OTHER MYTHS A...",HEIDI BOGHOSIAN,"""I HAVE NOTHING TO HIDE"": AND 20 OTHER MYTHS A...","""I HAVE NOTHING TO HIDE"": AND 20 OTHER MYTHS A...",2024-12-01
10733476,Digital,OverDrive,EBOOK,2024,12,1,"""I Have Nothing to Hide"": And 20 Other Myths A...",Heidi Boghosian,"Politics, Sociology, Nonfiction, Media Studies","Random House, Inc.",2021,9780807061275,EBOOK,"""I HAVE NOTHING TO HIDE"": AND 20 OTHER MYTHS A...",HEIDI BOGHOSIAN,"""I HAVE NOTHING TO HIDE"": AND 20 OTHER MYTHS A...","""I HAVE NOTHING TO HIDE"": AND 20 OTHER MYTHS A...",2024-12-01
4694838,Digital,OverDrive,EBOOK,2024,12,1,"""You Can Tell Just by Looking"": And 20 Other M...",Michael Bronski,"LGBTQIA+ (Nonfiction), Sociology, Nonfiction","Random House, Inc.",2022,9780807042465,EBOOK,"""YOU CAN TELL JUST BY LOOKING"": AND 20 OTHER M...",MICHAEL BRONSKI,"""YOU CAN TELL JUST BY LOOKING"": AND 20 OTHER M...","""YOU CAN TELL JUST BY LOOKING"": AND 20 OTHER M...",2024-12-01
9860031,Digital,OverDrive,EBOOK,2024,12,1,"""You Can Tell Just by Looking"": And 20 Other M...",Michael Bronski,"LGBTQIA+ (Nonfiction), Sociology, Nonfiction","Random House, Inc.",2022,9780807042465,EBOOK,"""YOU CAN TELL JUST BY LOOKING"": AND 20 OTHER M...",MICHAEL BRONSKI,"""YOU CAN TELL JUST BY LOOKING"": AND 20 OTHER M...","""YOU CAN TELL JUST BY LOOKING"": AND 20 OTHER M...",2024-12-01
4019869,Digital,OverDrive,EBOOK,2024,12,4,"""You Just Need to Lose Weight"": And 19 Other M...",Aubrey Gordon,"Self-Improvement, Sociology, Nonfiction","Random House, Inc.",2023,9780807006481,EBOOK,"""YOU JUST NEED TO LOSE WEIGHT"": AND 19 OTHER M...",AUBREY GORDON,"""YOU JUST NEED TO LOSE WEIGHT"": AND 19 OTHER M...","""YOU JUST NEED TO LOSE WEIGHT"": AND 19 OTHER M...",2024-12-01
7632033,Digital,OverDrive,EBOOK,2024,12,4,"""You Just Need to Lose Weight"": And 19 Other M...",Aubrey Gordon,"Self-Improvement, Sociology, Nonfiction","Random House, Inc.",2023,9780807006481,EBOOK,"""YOU JUST NEED TO LOSE WEIGHT"": AND 19 OTHER M...",AUBREY GORDON,"""YOU JUST NEED TO LOSE WEIGHT"": AND 19 OTHER M...","""YOU JUST NEED TO LOSE WEIGHT"": AND 19 OTHER M...",2024-12-01
572638,Digital,OverDrive,EBOOK,2024,12,3,#FashionVictim: A Novel,Amina Akhtar,"Fiction, Suspense, Thriller","Random House, Inc.",2018,9781683318354,EBOOK,#FASHIONVICTIM: A NOVEL,AMINA AKHTAR,#FASHIONVICTIM: A NOVEL,#FASHIONVICTIM: A NOVEL||AMINA AKHTAR,2024-12-01
9860951,Digital,OverDrive,EBOOK,2024,12,3,#FashionVictim: A Novel,Amina Akhtar,"Fiction, Suspense, Thriller","Random House, Inc.",2018,9781683318354,EBOOK,#FASHIONVICTIM: A NOVEL,AMINA AKHTAR,#FASHIONVICTIM: A NOVEL,#FASHIONVICTIM: A NOVEL||AMINA AKHTAR,2024-12-01

In [11]:
# Find titles that appear multiple times but have different ISBNs
digital_isbn_check = digital_checkouts[
    (digital_checkouts['materialtype'] == 'EBOOK') &
    (digital_checkouts['checkoutyear'] == 2024) &
    (digital_checkouts['checkoutmonth'] == 12)
].groupby('title').agg(
    row_count=('title', 'count'),
    unique_isbns=('isbn', 'nunique')
).reset_index()

# Duplicate titles with different ISBNs
different_digital_isbns = digital_isbn_check[
    (digital_isbn_check['row_count'] > 1) &
    (digital_isbn_check['unique_isbns'] > 1)
]

print(f"Titles with duplicates and different ISBNs: {len(different_digital_isbns):,}")

# Show sample rows from source data for these titles
sample_digital_titles = different_digital_isbns['title'].head(3).tolist()
digital_checkouts[
    (digital_checkouts['materialtype'] == 'EBOOK') &
    (digital_checkouts['checkoutyear'] == 2024) &
    (digital_checkouts['checkoutmonth'] == 12) &
    (digital_checkouts['title'].isin(sample_digital_titles))
].sort_values('title')

Titles with duplicates and different ISBNs: 972

,usageclass,checkouttype,materialtype,checkoutyear,checkoutmonth,checkouts,title,creator,subjects,publisher,publicationyear,isbn,materialtype_upper,title_clean,creator_clean,title_book_clean,work_key,month_date
201622,Digital,OverDrive,EBOOK,2024,12,2,'Twas the Night Before Christmas,Clement Clarke Moore,"Classic Literature, Juvenile Fiction, Juvenile...",HarperCollins Publishers Inc.,2011,9780547531175,EBOOK,'TWAS THE NIGHT BEFORE CHRISTMAS,CLEMENT CLARKE MOORE,'TWAS THE NIGHT BEFORE CHRISTMAS,'TWAS THE NIGHT BEFORE CHRISTMAS||CLEMENT CLAR...,2024-12-01
2805912,Digital,OverDrive,EBOOK,2024,12,2,'Twas the Night Before Christmas,Clement Clarke Moore,"Classic Literature, Juvenile Fiction, Juvenile...",HarperCollins Publishers Inc.,2011,9780547531175,EBOOK,'TWAS THE NIGHT BEFORE CHRISTMAS,CLEMENT CLARKE MOORE,'TWAS THE NIGHT BEFORE CHRISTMAS,'TWAS THE NIGHT BEFORE CHRISTMAS||CLEMENT CLAR...,2024-12-01
10064247,Digital,OverDrive,EBOOK,2024,12,3,'Twas the Night Before Christmas,Jane Chapman,"Juvenile Fiction, Juvenile Literature",Sourcebooks,2024,9781464222788,EBOOK,'TWAS THE NIGHT BEFORE CHRISTMAS,JANE CHAPMAN,'TWAS THE NIGHT BEFORE CHRISTMAS,'TWAS THE NIGHT BEFORE CHRISTMAS||JANE CHAPMAN,2024-12-01
366784,Digital,OverDrive,EBOOK,2024,12,3,1919,Eve L. Ewing,"Fiction, Poetry",Lightning Source Inc,2019,9781608466009,EBOOK,1919,EVE L. EWING,1919,1919||EVE L. EWING,2024-12-01
572554,Digital,OverDrive,EBOOK,2024,12,2,1919,John Dos Passos,"Fiction, Literature, Historical Fiction",Open Road Integrated Media,2016,9780544341456,EBOOK,1919,JOHN DOS PASSOS,1919,1919||JOHN DOS PASSOS,2024-12-01
4694180,Digital,OverDrive,EBOOK,2024,12,3,1919,Eve L. Ewing,"Fiction, Poetry",Lightning Source Inc,2019,9781608466009,EBOOK,1919,EVE L. EWING,1919,1919||EVE L. EWING,2024-12-01
9860867,Digital,OverDrive,EBOOK,2024,12,2,1919,John Dos Passos,"Fiction, Literature, Historical Fiction",Open Road Integrated Media,2016,9780544341456,EBOOK,1919,JOHN DOS PASSOS,1919,1919||JOHN DOS PASSOS,2024-12-01
199964,Digital,OverDrive,EBOOK,2024,12,68,1984,George Orwell,"Classic Literature, Fiction, Literature",HarperCollins Publishers Inc.,2011,9780547249643,EBOOK,1984,GEORGE ORWELL,1984,1984||GEORGE ORWELL,2024-12-01
364431,Digital,OverDrive,EBOOK,2024,12,1,1984,George Orwell,"Classic Literature, Fiction",Ink It Digital,2020,9789590308635,EBOOK,1984,GEORGE ORWELL,1984,1984||GEORGE ORWELL,2024-12-01
2804254,Digital,OverDrive,EBOOK,2024,12,68,1984,George Orwell,"Classic Literature, Fiction, Literature",HarperCollins Publishers Inc.,2011,9780547249643,EBOOK,1984,GEORGE ORWELL,1984,1984||GEORGE ORWELL,2024-12-01
4691827,Digital,OverDrive,EBOOK,2024,12,1,1984,George Orwell,"Classic Literature, Fiction",Ink It Digital,2020,9789590308635,EBOOK,1984,GEORGE ORWELL,1984,1984||GEORGE ORWELL,2024-12-01

### for the sake of this analysis, I'm interested in tracking checkouts per title<>creator, not per title edition (e.g. "Ramona the Brave" 1st edition was checked out once, 3rd edition checked out 3x, interested in tracking 4 checkouts across all editions.  Will keep data granular to edition, but analysis will be collapsed on unique titles.  work_key has been generated in the 02_cleaning notebook to reflect this.

# Title Cleaning

### Assess discrepancies between how book/ ebook titles, authors vary. try to get them as close as possible for string matching between the two

In [12]:
#import data

book_checkouts = physical_checkouts[
    (physical_checkouts['materialtype'] == 'BOOK')]

ebook_checkouts = digital_checkouts[
    (digital_checkouts['materialtype'] == 'EBOOK')]

### check book title formats

In [13]:
#identify common separators and how often they're used for formatting book title metadata

import re
from collections import Counter

def inspect_separator(sep, n=20):
    escaped = re.escape(sep)
    total_distinct = book_checkouts['title'].nunique()
    matches = book_checkouts[book_checkouts['title'].str.contains(escaped, na=False, regex=False)]
    distinct_matches = matches['title'].nunique()
    pct = distinct_matches / total_distinct * 100
    
    print(f"=== Titles containing '{sep}' ===")
    print(f"Distinct titles: {distinct_matches:,} of {total_distinct:,} ({pct:.1f}%)\n")
    
    sample = matches['title'].drop_duplicates().sample(min(n, distinct_matches))
    for title in sample:
        parts = [p.strip() for p in title.split(sep)]
        for i, part in enumerate(parts):
            print(f"  Part {i+1}: {part[:80]}")
        print()

for sep in ['/', ':', ';', ',', '||']:
    inspect_separator(sep)
    print('=' * 60)

=== Titles containing '/' ===
Distinct titles: 469,746 of 517,224 (90.8%)

  Part 1: The art and craft of judging; the decisions of Judge Learned Hand
  Part 2: edited and annotated, with an introd., by Hershel Shanks.

  Part 1: How to change minds about our changing climate : let science do the talking the
  Part 2: Seth B. Darling and Douglas L. Sisterson ; illustrations by Sarah M. Sisterson.

  Part 1: Great football writing : Sports illustrated 1954-2006
  Part 2: edited by Rob Fleder.

  Part 1: Inner way : Eastern Christian spiritual direction
  Part 2: Joseph J. Allen.

  Part 1: What is the AIDS crisis?
  Part 2: by Nico Medina ; illustrated by Tim Foley.

  Part 1: Pauline Kael : a life in the dark
  Part 2: Brian Kellow.

  Part 1: 1776
  Part 2: David McCullough.

  Part 1: Matisse
  Part 2: Diebenkorn
  Part 3: edited by Janet Bishop and Katherine Rothkopf.

  Part 1: The Paragon Hotel
  Part 2: Lyndsay Faye.

  Part 1: Some Spanish-American poets
  Part 2: translated by Alice Stone Blackwell; with an introduction and notes by Isaac Gol

  Part 1: A timeshare
  Part 2: Margaret Ross.

  Part 1: History of a pleasure seeker
  Part 2: Richard Mason.

  Part 1: Pranklopedia : the funniest, grossest, craziest, not-mean pranks on the planet!
  Part 2: Julie Winterbottom ; illustrated by Robb Allen.

  Part 1: Frommer's 500 places where you can make a difference
  Part 2: by Andrew Mersmann ; with Carrie Harvanek & Kisha Ferguson.

  Part 1: Kage no keifu : Toyotomi-ke hōkai
  Part 2: Sugimoto Sonoko cho.

  Part 1: 2019 nian Zhongguo zhen tan tui li xiao shuo jing xuan
  Part 2: Han Xuan, xuan bian.

  Part 1: Catch that crook!
  Part 2: by Laura Hitchcock ; illustrated by Elisabetta Melaranci and Giulia Priori.

  Part 1: That's not funny, that's sick : the National lampoon and the comedy insurgents w
  Part 2: Ellin Stein.

  Part 1: Record of Grancrest War. 5
  Part 2: original story by Ryo Mizuno ; story & art by Makoto Yotsuba ; character design

  Part 1: Merry Witchmas
  Part 2: by Petrell Marie Özbay and Tess La Bella ; illustrated by Sonya Abby.

============================================================
=== Titles containing ':' ===
Distinct titles: 233,360 of 517,224 (45.1%)

  Part 1: Fun home
  Part 2: a family tragicomic / Alison Bechdel.

  Part 1: Big love cooking
  Part 2: 75 recipes for satisfying, shareable comfort food / Joey Campanaro with Theresa

  Part 1: The visible word
  Part 2: experimental typography and modern art, 1909-1923 / Johanna Drucker.

  Part 1: Anthology of amazing women
  Part 2: trailblazers who dared to be different / written by Sandra Lawrence ; illustrate

  Part 1: Christianity
  Part 2: the origins of a pagan religion / Philippe Walter ; translated by Jon E. Graham.

  Part 1: Princess Masako
  Part 2: prisoner of the chrysanthemum throne / Ben Hills.

  Part 1: Claim of privilege
  Part 2: a mysterious plane crash, a landmark Supreme Court case, and the rise of state s

  Part 1: Anti-diet
  Part 2: reclaim your time, money, well-being, and happiness through intuitive eating / C

  Part 1: The great influenza
  Part 2: the true story of the deadliest pandemic in history / John M. Barry ; adapted by

  Part 1: The pulse of mixed media
  Part 2: secrets and passions of 100 artists revealed / Seth Apter.

  Part 1: A great aridness
  Part 2: climate change and the future of the American southwest / William deBuys.

  Part 1: Three free sins
  Part 2: God's not mad at you / Steve Brown.

  Part 1: White Dog Cafe cookbook
  Part 2: multicultural recipes and tales of adventure from Philadelphia's revolutionary r

  Part 1: The Beach Boys
  Part 2: the definitive diary of America's greatest band, on stage and in the studio / Ke

  Part 1: A box full of tales
  Part 2: easy ways to share library resources through story boxes / Kathy MacMillan.

  Part 1: Like, literally, dude
  Part 2: arguing for the good in bad English / Valerie Fridland.

  Part 1: St. Thérèse of Lisieux
  Part 2: essential writings / selected with an introduction by Mary Frohlich.

  Part 1: Great good desserts naturally!
  Part 2: secrets of sensational sin-free sweets / Fran Costigan.

  Part 1: Mad as hell
  Part 2: the life and work of Paddy Chayefsky / by Shaun Considine.

  Part 1: Roosevelt and Stalin
  Part 2: portrait of a partnership / Susan Butler.

============================================================
=== Titles containing ';' ===
Distinct titles: 144,286 of 517,224 (27.9%)

  Part 1: The perennial care manual : a plant-by-plant guide : what to do & when to do it
  Part 2: photography by Rob Cardillo.

  Part 1: Daredevil. Black armor / D.G Chichester, writer
  Part 2: JP Mayer, inker
  Part 3: VC's Clayton Cowles, letterer
  Part 4: Netho Diaz, penciler
  Part 5: Andrew Dalhouse, colorist.

  Part 1: Eva and Sadie and the worst haircut ever! / by Jeff Cohen
  Part 2: illustrated by Elanna Allen.

  Part 1: Down at the Dino Wash Deluxe / by Tim Myers
  Part 2: illustrated by Macky Pamintuan.

  Part 1: The log from the Sea of Cortez / John Steinbeck
  Part 2: introduction by Richard Astro.

  Part 1: Washington / by Ann Heinrichs
  Part 2: illustrated by Matt Kania.

  Part 1: Ideas (casi) geniales / Liz Pichon
  Part 2: traducción al castellano, Daniel Cortés Coronas.

  Part 1: Roots : the definitive compendium with more than 225 recipes / Diane Morgan
  Part 2: foreword by Deborah Madison
  Part 3: photographs by Antonis Achilleos.

  Part 1: Let's cook it right
  Part 2: good health comes from good cooking [by] Adelle Davis ...

  Part 1: The vanishing race, the last great Indian council : a record in picture and stor
  Part 2: the concept of Rodman Wanamaker
  Part 3: this volume is illustrated with eighty photogravures of Indian chiefs and Indian

  Part 1: The rough guide to Belgium and Luxembourg / written and researched by Phil Lee a
  Part 2: with additional contributions from Loïk Dal Molin and Suzy Sumner.

  Part 1: Valley of the kings / edited by Kent R. Weeks
  Part 2: photographs by Araldo De Luca
  Part 3: editorial production, Valeria Manferto De Fabianis, Laura Accomazzo
  Part 4: graphic design, Clara Zanotti.

  Part 1: Plays one / Yasmina Reza
  Part 2: [translated by Christopher Hampton].

  Part 1: An organizer's tale : speeches / Cesar Chavez
  Part 2: edited with an introduction by Ilan Stavans.

  Part 1: Dark watch / Clive Cussler
  Part 2: with Jack Du Brul.

  Part 1: Writings / S. J. Perelman
  Part 2: Adam Gopnik, editor.

  Part 1: Cut paper, silhouettes and stencils
  Part 2: an instruction book. / Translated by Alba Lorman.

  Part 1: Plays one / Christopher Hampton
  Part 2: introduced by the author.

  Part 1: A captain's war : the letters and diaries of William H.S. Burgwyn, 1861-1865 / e
  Part 2: foreword by Richard J. Sommers.

  Part 1: Classic Indian vegetarian and grain cooking / Julie Sahni
  Part 2: illustrations by Richard Pfanz.

============================================================
=== Titles containing ',' ===
Distinct titles: 124,622 of 517,224 (24.1%)

  Part 1: Judge Dredd : the complete case files. 03 / [John Wagner
  Part 2: Pat Mills
  Part 3: writers ; Mike McMahon ... [and others]
  Part 4: artists ; Tom Frame ... [et al.]
  Part 5: letters ; Brian Bolland
  Part 6: cover artist].

  Part 1: Recover! : stop thinking like an addict and reclaim your life with the perfect p
  Part 2: with Ilse Thompson.

  Part 1: Venice & the Veneto / this edition written and researched by Christian Bonetto
  Part 2: Paula Hardy.

  Part 1: Robert Irwin Getty garden / Lawrence Weschler ; garden photography
  Part 2: Becky Cohen.

  Part 1: Women
  Part 2: fire
  Part 3: and dangerous things : what categories reveal about the mind / George Lakoff.

  Part 1: Georges Braque / by Jean Leymarie ; with contributions by Jean Leymarie
  Part 2: Magdalena M. Moeller and Carla Schulz-Hoffmann.

  Part 1: ILLM War Plan Orange : the U.S. strategy to defeat Japan
  Part 2: 1897-1945

  Part 1: Genji and Heike : selections from The tale of Genji and The tale of the Heike /
  Part 2: with introductions
  Part 3: by Helen Craig McCullough.

  Part 1: Glengarry's way
  Part 2: and other studies / by William Roughead ... With nine illustrations.

  Part 1: Clark Howard's living large for the long haul : consumer-tested ways to overhaul
  Part 2: increase your savings
  Part 3: and get your life back on track / Clark Howard ; with Mark Meltzer and Theo Thim

  Part 1: One piece. Vol. 61
  Part 2: Romance dawn for the new world / story and art by Eiichiro Oda ; [english adapta
  Part 3: Lance Caselman ; translation
  Part 4: Laabaman
  Part 5: HC Language Solutions
  Part 6: Inc. ; touch-up art & lettering
  Part 7: Vanessa Satone].

  Part 1: Milan & the lakes / contributor
  Part 2: Monica Torri ; English translation
  Part 3: Richard Pierce.

  Part 1: Saying Kaddish : how to comfort the dying
  Part 2: bury the dead
  Part 3: and mourn as a Jew / Anita Diamant.

  Part 1: Home hydroponics : small-space DIY growing systems : for the kitchen
  Part 2: dining room
  Part 3: living room
  Part 4: bedroom
  Part 5: and bath / Tyler Baras.

  Part 1: Collection of official documents on the San Juan imbroglio
  Part 2: 1859-1872 / The National Guard
  Part 3: State of Washington.

  Part 1: The Three Stooges. 1
  Part 2: Bed bugged! and other stories / George Gladir
  Part 3: Jim Salicrup
  Part 4: writers ; Stan Goldberg
  Part 5: artist ; Laurie E. Smith
  Part 6: colorist.

  Part 1: Justice League. Generation lost. Volume two / Judd Winick
  Part 2: writer ; Joe Bennett
  Part 3: Fernando Dagnino
  Part 4: Aaron Lopresti
  Part 5: pencillers ; Jack Jadson ... [and others]
  Part 6: inkers ; Hi-Fi
  Part 7: colorist ; Sal Cipriano ... [et al.]
  Part 8: letterers.

  Part 1: Volkswagen Rabbit/Jetta diesel service manual
  Part 2: 1977
  Part 3: 1978
  Part 4: 1979
  Part 5: 1980
  Part 6: 1981
  Part 7: 1982
  Part 8: including pickup truck.

  Part 1: Ibang buhay
  Part 2: ibang pag-ibig / Edgar Reyes.

  Part 1: Charleston
  Part 2: crossroads of history : a story of the South Carolina low country / by Isabella

============================================================
=== Titles containing '||' ===
Distinct titles: 0 of 517,224 (0.0%)

============================================================

In [14]:
# evaluate how often splitting title on / will be correct

# Split on / and evaluate each part
def evaluate_slash_splits(df, title_col='title'):
    titles_with_slash = df[df[title_col].str.contains('/', na=False, regex=False)][title_col].drop_duplicates()
    
    total = len(titles_with_slash)
    print(f"Total distinct titles with '/': {total:,}\n")
    
    # Heuristics for when / is likely IN the title vs a separator
    likely_in_title = titles_with_slash[
        titles_with_slash.str.contains(r'\d+/\d+', na=False)  # fractions like 1/2
        | titles_with_slash.str.contains(r'[A-Z]/[A-Z]', na=False)  # acronyms like AC/DC
        | titles_with_slash.str.contains(r'\w/\w', na=False)  # no spaces around slash
    ]
    
    likely_separator = titles_with_slash[
        titles_with_slash.str.contains(r'\s/\s', na=False)  # spaces on both sides
    ]

    print(f"Likely separator (spaces on both sides):  {len(likely_separator):,} ({len(likely_separator)/total*100:.1f}%)")
    print(f"Likely in title (no spaces / acronym):    {len(likely_in_title):,} ({len(likely_in_title)/total*100:.1f}%)")
    print(f"Ambiguous (other):                        {total - len(likely_separator) - len(likely_in_title):,} ({(total - len(likely_separator) - len(likely_in_title))/total*100:.1f}%)")

    print(f"\n=== Sample: likely separator ===")
    for title in likely_separator.sample(min(10, len(likely_separator))):
        parts = title.split('/')
        print(f"  Part 1: {parts[0].strip()[:60]}")
        print(f"  Part 2: {'/'.join(parts[1:]).strip()[:60]}")
        print()

    print(f"=== Sample: likely in title ===")
    for title in likely_in_title.sample(min(10, len(likely_in_title))):
        print(f"  {title[:80]}")
        print()

    #return ambiguous responses

    ambiguous = titles_with_slash[
        ~titles_with_slash.isin(likely_separator) & 
        ~titles_with_slash.isin(likely_in_title)
    ]
    
    print(f"=== Sample: ambiguous ===")
    for title in ambiguous.sample(min(10, len(ambiguous))):
        print(f"  {title[:80]}")
        print()
    
    return ambiguous

ambiguous = evaluate_slash_splits(book_checkouts)

Total distinct titles with '/': 469,746

Likely separator (spaces on both sides):  468,925 (99.8%)
Likely in title (no spaces / acronym):    2,610 (0.6%)
Ambiguous (other):                        -1,789 (-0.4%)

=== Sample: likely separator ===
  Part 1: Invisible men : the trailblazing Black artists of comic book
  Part 2: Ken Quattro.

  Part 1: Alfie's ABC
  Part 2: Shirley Hughes.

  Part 1: The nightmare brigade. Vol. 2, Into the woods
  Part 2: story, Franck Thilliez ; art, Yomgui Dumont ; color, Drac.

  Part 1: Tin man
  Part 2: Sarah Winman.

  Part 1: Arts and crafts rugs for craftsman interiors : the Crab Tree
  Part 2: Linda Parry and David Cathers ; with Diane Boucher, Ann Lane

  Part 1: Alice Sadie Celine
  Part 2: Sarah Blakley-Cartwright.

  Part 1: Ireland
  Part 2: author: Allanah Hopkin.

  Part 1: Jana goes wild
  Part 2: Farah Heron.

  Part 1: Shashin o tsukatte ehon o tsukurō !
  Part 2: Nakagawa Motoko, Wada Naoto.

  Part 1: Firestorm
  Part 2: Rachel Grant.

=== Sample: likely in title ===
  Creating a Chicana/o Red Road to decolonization & Aztlan : a roadmap towards a n

  Limbo. [1] / created by Caspar Wijngaard & Dan Watters ; script, Dan Watters ; a

  Orange planet. 3/4/5 / Haruka Fukushima ; translated and adapted by Kaya Laterma

  Marisol McDonald doesn't match = Marisol McDonald no combina / story/cuento, Mon

  The 80/20 individual : how to accomplish more by doing less -- the nine essentia

  Gun games : a Decker/Lazarus novel / Faye Kellerman.

  Onŭl ŭn ch'ingch'an patko sip'ŭn nal! / Chenip'ŏ K. Man, kŭl/kŭrim ; Yang Pyŏng-

  Boruto : Naruto next generations. Volume 2, Stupid old man!! / creator/superviso

  Noraneko no Pora / Furiya Kayoko, saku/e.

  ILLM Marine engineering/log: v.85 pt. 1: Jan-June 1980

=== Sample: ambiguous ===
  ILLM world of programming languages /

  Party monster : a fabulous but true tale of murder in clubland/ James St. James.

  ILLM No truce with the furies /

  ILLM school that cared : a story of the Marva Collins Preparatory School of Cinc

  ILLM Ostkrieg : Hitler's war of extermination in the East /

  Blueprint for space : science fiction to science fact/ edited by Frederick I. Or

  Paper cutting : 25 beautiful and practical projects shown step by step/ Stewart

  ILLM Fighting inflammation : how to stop the damage before it compromises your h

  ILLM Echoes of mutiny : race, surveillance, and Indian anticolonialism in North

  ILLM Surmounting the barricades : women in the Paris Commune /

### only returning the first part of the book title before ' / ' separator 
### addresses 99.8% of its use as the most common separator character.

### check ebook formats

In [15]:
#identify common separators and how often they're used for formatting book title metadata

import re
from collections import Counter

def inspect_separator(sep, n=20):
    escaped = re.escape(sep)
    total_distinct = ebook_checkouts['title'].nunique()
    matches = ebook_checkouts[ebook_checkouts['title'].str.contains(escaped, na=False, regex=False)]
    distinct_matches = matches['title'].nunique()
    pct = distinct_matches / total_distinct * 100
    
    print(f"=== Titles containing '{sep}' ===")
    print(f"Distinct titles: {distinct_matches:,} of {total_distinct:,} ({pct:.1f}%)\n")
    
    sample = matches['title'].drop_duplicates().sample(min(n, distinct_matches))
    for title in sample:
        parts = [p.strip() for p in title.split(sep)]
        for i, part in enumerate(parts):
            print(f"  Part {i+1}: {part[:80]}")
        print()

for sep in ['/', ':', ';', ',', '||']:
    inspect_separator(sep)
    print('=' * 60)

=== Titles containing '/' ===
Distinct titles: 1,310 of 270,972 (0.5%)

  Part 1: Dolphins
  Part 2: Los delfines

  Part 1: Making New Friends with Baby King
  Part 2: 和小金金做朋友

  Part 1: Tempted: Little Miss Innocent?
  Part 2: Annie, Get Your Guy
  Part 3: Messing Around with Max

  Part 1: Lolo and Birdie: I Want More!
  Part 2: ¡Quiero Más!

  Part 1: laget hiyt toxwum
  Part 2: Herring to Huckleberries

  Part 1: Home for the Holidays: The Forgetful Bride
  Part 2: When Christmas Comes

  Part 1: Denver
  Part 2: Boulder and Colorado's Front Range: A Comprehensive Hiking Guide

  Part 1: Butterflies on Carmen Street
  Part 2: Mariposas en la Calle Carmen

  Part 1: ¡Este es el día!
  Part 2: This Is the Day! (Bilingual)

  Part 1: Sizzle: Buchanan
  Part 2: Renard
  Part 3: MacKenna Series, Book 8

  Part 1: Phantom Waltz: Kendrick
  Part 2: Coulter
  Part 3: Harrigan Series, Book 2

  Part 1: Shielding Riley: Army Delta Force
  Part 2: Military Romance

  Part 1: 龟兔赛跑
  Part 2: The Tortoise And The Hare

  Part 1: A Murder Hatched: Murder with Peacocks
  Part 2: Murder with Puffins

  Part 1: Haven: A Bishop
  Part 2: Special Crimes Unit Novel: Bishop
  Part 3: Special Crimes Unit Series, Book 13

  Part 1: Ten Lords A-Leaping: Robert Amiss
  Part 2: BaronessJack Troutbeck Mysteries Series, Book 6

  Part 1: The Girls Get Even: Boy
  Part 2: Girl Battle Series, Book 2

  Part 1: Thank You, Mr. Panda
  Part 2: Gracias, Sr. Panda

  Part 1: Back on Track (Disney
  Part 2: Pixar Cars 3)

  Part 1: The Ritual Bath: The First Decker
  Part 2: Lazarus Novel

============================================================
=== Titles containing ':' ===
Distinct titles: 160,730 of 270,972 (59.3%)

  Part 1: Days of Awe
  Part 2: A Novel

  Part 1: Alien Retribution
  Part 2: Zerconian Warriors, #13

  Part 1: Truevine
  Part 2: Two Brothers, a Kidnapping, and a Mother's Quest
  Part 3: A True Story of the Jim Crow South

  Part 1: The Menagerie
  Part 2: Krakens and Lies

  Part 1: William Howard Taft
  Part 2: The 27th President, 1909-1913

  Part 1: Cover Your Assets
  Part 2: Tucker Sinclair Series, Book 2

  Part 1: The Devil by Name
  Part 2: A Novel

  Part 1: The Frozen People
  Part 2: A Mystery

  Part 1: Curlfriends
  Part 2: New in Town

  Part 1: Soulmates
  Part 2: A Novel

  Part 1: Killer in the Carriage House
  Part 2: Victorian Village Mystery Series, Book 2

  Part 1: In This Garden
  Part 2: Exploration in Mixed-Media Visual Narrative

  Part 1: Party Animals
  Part 2: A Cranky Chicken Book 2

  Part 1: Don't Kill the Messenger
  Part 2: Messenger Series, Book 1

  Part 1: Omega Games
  Part 2: A Stardoc Novel
  Part 3: Stardoc Series, Book 8

  Part 1: Highland Protector
  Part 2: Murray Family Series, Book 12

  Part 1: Great Tales from English History, Book 2
  Part 2: Joan of Arc, the Princes in the Tower, Bloody Mary, Oliver Cromwell, Sir Isaac N

  Part 1: Never Call It Loving
  Part 2: The Immortal Love Story of Kitty OShea and Charles Parnell

  Part 1: The Dealer
  Part 2: CHERUB Series, Book 2

  Part 1: Honor
  Part 2: The Breaking Point

============================================================
=== Titles containing ';' ===
Distinct titles: 321 of 270,972 (0.1%)

  Part 1: Love's Tender Fury / Love Me, Marietta / When Love Commands: Love's Tender Fury
  Part 2: Love Me, Marietta
  Part 3: and When Love Commands

  Part 1: His Dark Materials Omnibus: The Golden Compass
  Part 2: The Subtle Knife
  Part 3: The Amber Spyglass

  Part 1: Treaties, Trenches, Mud, and Blood: (A World War I Tale)
  Part 2: Nathan Hale's Hazardous Tales, Book 4

  Part 1: Murder Is Forever, Volume 1: Murder, Interrupted
  Part 2: Mother of All Murders

  Part 1: The Stargirl Collection: Stargirl
  Part 2: Love, Stargirl

  Part 1: Why?과학087-요리과학(2판
  Part 2: Why? Cooking Science)

  Part 1: 'Til The World Ends: Dawn of Eden
  Part 2: Thistle & Thorne
  Part 3: Sun Storm

  Part 1: Chasing My Cure: A Doctor's Race to Turn Hope into Action
  Part 2: A Memoir

  Part 1: The Kill Order: Book Four
  Part 2: Origin

  Part 1: Monticello: A Daughter and Her Father
  Part 2: A Novel

  Part 1: The Copenhagen Trilogy: Childhood
  Part 2: Youth
  Part 3: Dependency: The Copenhagen Trilogy, Books 1-3

  Part 1: Three Witch Tales: A Matter-of-Fact Magic Collection: Witch's Cat
  Part 2: The Witch's Buttons
  Part 3: The Witch's Garden

  Part 1: The Battle of Britain: Five Months That Changed History
  Part 2: May-October 1940

  Part 1: Bead Weaving and Embroidery with Miyuki Beads: Instructions for Brick Stitch, Pe
  Part 2: 100 Weaving Patterns

  Part 1: The Oresteia: Agamemnon
  Part 2: The Libation Bearers
  Part 3: The Eumenides

  Part 1: The Three Theban Plays: Antigone
  Part 2: Oedipus the King
  Part 3: Oedipus at Colonus

  Part 1: The Summer Queen: A Novel of Eleanor of Aquitaine
  Part 2: Eleanor of Aquitaine Series, Book 1

  Part 1: Christmas in Cedar Cove: Cedar Cover Series, Books 5.5
  Part 2: 8.5

  Part 1: Vegan Wholesome: High-Protein Meals and Snacks to Energize and Nourish
  Part 2: A Cookbook

  Part 1: King's Blood: Kingdom at Sea
  Part 2: Maelstrom
  Part 3: Voice of Blood: The Kinsman Chronicles Series, Book 2

============================================================
=== Titles containing ',' ===
Distinct titles: 76,569 of 270,972 (28.3%)

  Part 1: 101 Ways to Be Less Stressed: Simple Self-Care Strategies to Boost Your Mind
  Part 2: Mood
  Part 3: and Mental Health

  Part 1: Taken: Taken Series
  Part 2: Book 1

  Part 1: Alien Mischief: A Scifi Romance: Alternative Futures Box Set
  Part 2: #1

  Part 1: Thrones
  Part 2: Dominations: Lord Peter Wimsey Series
  Part 3: Book 1

  Part 1: First Degree: Andy Carpenter Series
  Part 2: Book 2

  Part 1: Cursed Luck
  Part 2: Book 1

  Part 1: Murder on the Orient Express: Hercule Poirot Series
  Part 2: Book 9

  Part 1: The Mexican Slow Cooker: Recipes for Mole
  Part 2: Enchiladas
  Part 3: Carnitas
  Part 4: Chile Verde Pork
  Part 5: and More Favorites

  Part 1: The Haunted: The Haunted Series
  Part 2: Book 1

  Part 1: Merlin: Young Merlin Series
  Part 2: Book 3

  Part 1: Effective Writing for Business
  Part 2: College
  Part 3: and Life

  Part 1: Trout Fishing in America
  Part 2: the Pill versus the Springhill Mine Disaster
  Part 3: and In Watermelon Sugar

  Part 1: Shut Up
  Part 2: This Is Serious

  Part 1: The Claiming of Sleeping Beauty: Sleeping Beauty Series
  Part 2: Book 1

  Part 1: Evil Without a Face: Sweet Justice Series
  Part 2: Book 1

  Part 1: Sarah's Quilt: A Novel of Sarah Agnes Prine and the Arizona Territories
  Part 2: 1906

  Part 1: Rilla of Ingleside: Anne of Green Gables Series
  Part 2: Book 8

  Part 1: The Assassin: Ryan Kealey Series
  Part 2: Book 2

  Part 1: Luke: The Malloys of Montana Series
  Part 2: Book 2

  Part 1: Synchronized Sorcery: Witchcraft Mystery Series
  Part 2: Book 11

============================================================
=== Titles containing '||' ===
Distinct titles: 0 of 270,972 (0.0%)

============================================================

### ebook titles don't seem to have separators with additional metadata and just contain the titles/ captions

## EBook Title Cleaning - check frequency of parentheses containing noise

In [16]:
processed_dir = '/Users/audriswong/data-portfolio/projects/seattle-checkouts/data/processed'

#import data
book_checkouts = pd.read_parquet(f'{processed_dir}/book_checkouts.parquet').rename(columns={'title_clean': 'title'}) 
ebook_checkouts = pd.read_parquet(f'{processed_dir}/ebook_checkouts.parquet').rename(columns={'title_clean': 'title'})

In [17]:
##worth removing extra content in the parentheses?  e.g. (Pulitzer Prize, Oprah's Book Club)

import re
from collections import Counter

# Extract all parenthetical content from ebook titles
parens_content = []

for title in ebook_checkouts['title'].dropna():
    matches = re.findall(r'\(([^)]+)\)', str(title))
    parens_content.extend(matches)

parens_counts = Counter(parens_content)
print(f"=== Ebook Title Breakdown ===")
print(f"Total parenthetical instances: {len(parens_content):,}")
print(f"Distinct parenthetical values: {len(parens_counts):,}")
print("\n=== Most common parenthetical content ===")
for content, count in parens_counts.most_common(30):
    print(f"{count:>8,} | {content[:80]}")

#book titles
parens_content = []

for title in book_checkouts['title'].dropna():
    matches = re.findall(r'\(([^)]+)\)', str(title))
    parens_content.extend(matches)

parens_counts = Counter(parens_content)
print(f"=== Book Title Breakdown ===")
print(f"Total parenthetical instances: {len(parens_content):,}")
print(f"Distinct parenthetical values: {len(parens_counts):,}")
print("\n=== Most common parenthetical content ===")
for content, count in parens_counts.most_common(30):
    print(f"{count:>8,} | {content[:80]}")

=== Ebook Title Breakdown ===
Total parenthetical instances: 112,073
Distinct parenthetical values: 3,750

=== Most common parenthetical content ===
   2,668 | A GRAPHIC NOVEL
   1,636 | WORLD DIGITAL LIBRARY EDITION
   1,608 | AUBREY/MATURIN NOVELS
   1,573 | THOMAS & FRIENDS
   1,513 | 2003
   1,276 | BARBIE
     970 | ALMOST
     839 | 2014
     820 | MOSTLY
     747 | WITH BONUS CONTENT
     703 | 2012
     691 | PENGUIN CLASSICS DELUXE EDITION
     650 | STAR WARS
     646 | 2015
     588 | WITH AUDIO RECORDING
     575 | NOVEL
     571 | REVISED AND UPDATED
     565 | DC SUPER FRIENDS
     538 | WORLD DIGITAL LIBRARY
     489 | BOOK 1
     486 | PULITZER PRIZE WINNER
     472 | OPRAH'S BOOK CLUB
     470 | A NOVEL
     443 | 2013
     433 | SESAME STREET
     407 | MOVIE TIE-IN
     404 | SPANISH EDITION
     384 | READ-ALOUD
     383 | SCHOLASTIC GOLD
     365 | A COOKBOOK
=== Book Title Breakdown ===
Total parenthetical instances: 73,089
Distinct parenthetical values: 3,298

=== Most common parenthetical content ===
  17,357 | LARGE PRINT
     910 | ALMOST
     900 | MOSTLY
     845 | NOT
     731 | COGAT
     412 | K
     260 | COGAT*
     257 | SORT OF
     254 | UN
     236 | PROBABLY
     227 | ISH
     221 | AND THE SUBSEQUENT ASSAULT OF THE EQUALLY EVIL LUNCHROOM ZOMBIE NERDS
     215 | AND WHAT THE NEIGHBORS THOUGHT
     214 | WITH RECIPES
     213 | THE BOOK
     212 | AND THEIR PARENTS
     209 | AND DRAGONS
     203 | THAT NO ONE BOTHERS TO TELL YOU
     202 | AND EVERYTHING IN BETWEEN
     183 | S
     175 | STILL
     165 | VERY
     157 | A LOVE STORY
     144 | AND POKEY!
     143 | TE WAIPOUNAMU
     142 | AUTISM SPECTRUM DISORDER
     141 | EFT
     139 | ABOUT EVERYTHING!
     138 | AND OTHER LESSONS I'VE LEARNED
     132 | 1977-2002

In [18]:
# Classify parenthetical content into categories
def classify_paren(content):
    c = content.lower().strip()
    
    if re.search(r'\d{4}', c):
        return 'Year/Date'
    elif any(w in c for w in ['prize', 'award', 'winner', 'pulitzer', 'booker', 'newbery', 'caldecott', 'national book']):
        return 'Award/Prize'
    elif any(w in c for w in ['book club', 'reese', 'oprah', 'good morning america', 'gma', 'today show']):
        return 'Book Club'
    elif any(w in c for w in ['audio', 'unabridged', 'abridged', 'narrated', 'read by']):
        return 'Audio Details'
    elif any(w in c for w in ['bonus', 'excerpt', 'preview', 'includes', 'with ', 'enhanced', 'extra']):
        return 'Bonus Content'
    elif any(w in c for w in ['book 1', 'book 2', 'book 3', 'vol', 'volume', 'part ', 'series', '#']):
        return 'Series/Volume'
    elif any(w in c for w in ['edition', 'revised', 'updated', 'expanded', 'anniversary']):
        return 'Edition Info'
    elif any(w in c for w in ['translation', 'translated', 'adapted']):
        return 'Translation'
    elif any(w in c for w in ['illustrated', 'illustrations', 'pictures']):
        return 'Illustration Info'
    elif any(w in c for w in ['novel', 'memoir', 'story', 'tales', 'poems', 'essays']):
        return 'Likely Title Content'
    elif len(c.split()) <= 3:
        return 'Short — likely title content'
    else:
        return 'Other/Unclear'

# Apply classification
paren_classified = Counter()
paren_examples   = {}

for title in ebook_checkouts['title'].dropna():
    matches = re.findall(r'\(([^)]+)\)', str(title))
    for match in matches:
        category = classify_paren(match)
        paren_classified[category] += 1
        if category not in paren_examples:
            paren_examples[category] = []
        if len(paren_examples[category]) < 5:
            paren_examples[category].append(f"{match[:60]} <- {title[:60]}")

total = sum(paren_classified.values())
print(f"=== Parenthetical Content Categories ===\n")
for category, count in sorted(paren_classified.items(), key=lambda x: x[1], reverse=True):
    pct = count / total * 100
    print(f"{count:>8,} ({pct:>5.1f}%)  {category}")
    for ex in paren_examples.get(category, []):
        print(f"            e.g. {ex}")
    print()

=== Parenthetical Content Categories ===

  42,457 ( 37.9%)  Short — likely title content
            e.g. AND JOKES! <- HEIDEGGER AND A HIPPO WALK THROUGH THOSE PEARLY GATES: USING
            e.g. STILL <- HOW TO BE EVERYTHING: A GUIDE FOR THOSE WHO (STILL) DON'T KN
            e.g. ALMOST <- THE JESUIT GUIDE TO (ALMOST) EVERYTHING: A SPIRITUALITY FOR
            e.g. STILL <- YES WE (STILL) CAN: POLITICS IN THE AGE OF OBAMA, TWITTER, A
            e.g. FAIRLY <- RED: THE (FAIRLY) TRUE TALE OF RED RIDING HOOD

  23,087 ( 20.6%)  Other/Unclear
            e.g. DC SUPER HERO GIRLS <- HARLEY QUINN AT SUPER HERO HIGH (DC SUPER HERO GIRLS)
            e.g. NOT NECESSARILY IN THAT ORDER <- TRADING BASES: A STORY ABOUT WALL STREET, GAMBLING, AND BASE
            e.g. THE FAULT IN OUR STARS <- BAJO LA MISMA ESTRELLA: (THE FAULT IN OUR STARS)
            e.g. BUT NOT TOO GOOD-FOR-YOU <- HEALTHYISH: A COOKBOOK WITH SERIOUSLY SATISFYING, TRULY SIMP
            e.g. AND OTHER GOOD STUFF <- EXCELLENT EXCUSES (AND OTHER GOOD STUFF)

  12,019 ( 10.7%)  Series/Volume
            e.g. CHINA BAYLES MYSTERY #27 <- A PLAIN VANILLA MURDER: (CHINA BAYLES MYSTERY #27)
            e.g. VOLUME 2 <- THE STORY OF THE WORLD: HISTORY FOR THE CLASSICAL CHILD: THE
            e.g. LOA #317 <- WENDELL BERRY: ESSAYS 1993-2017 (LOA #317)
            e.g. VOLUME 1: ERAGON <- THE FORK, THE WITCH, AND THE WORM: TALES FROM ALAGAËSIA (VOL
            e.g. VOLUME BOOK 9 <- TREASON'S HARBOUR (VOLUME BOOK 9)  (AUBREY/MATURIN NOVELS)

   9,375 (  8.4%)  Edition Info
            e.g. PENGUIN CLASSICS DELUXE EDITION <- THE AENEID: (PENGUIN CLASSICS DELUXE EDITION)
            e.g. PAPER TOWNS—SPANISH-LANGUAGE EDITION <- CIUDADES DE PAPEL: (PAPER TOWNS—SPANISH-LANGUAGE EDITION)
            e.g. SECOND REVISED EDITION <- THE STORY OF THE WORLD: HISTORY FOR THE CLASSICAL CHILD: THE
            e.g. WORLD DIGITAL LIBRARY EDITION <- LES MISERABLES (WORLD DIGITAL LIBRARY EDITION)
            e.g. WORLD DIGITAL LIBRARY EDITION <- A LITTLE PRINCESS (WORLD DIGITAL LIBRARY EDITION)

   8,766 (  7.8%)  Likely Title Content
            e.g. A LOVE STORY <- THE SEVEN TORMENTS OF AMY AND CRAIG (A LOVE STORY)
            e.g. GRAPHIC NOVEL <- ANGEL CATBIRD VOLUME 1 (GRAPHIC NOVEL)
            e.g. GRAPHIC NOVEL <- FIGHT CLUB 2 (GRAPHIC NOVEL)
            e.g. STORY OF THE WORLD <- THE STORY OF THE WORLD: HISTORY FOR THE CLASSICAL CHILD: THE
            e.g. AUBREY/MATURIN NOVELS <- TREASON'S HARBOUR (VOLUME BOOK 9)  (AUBREY/MATURIN NOVELS)

   6,167 (  5.5%)  Year/Date
            e.g. 2012 <- SAGA (2012), VOLUME 3
            e.g. 2003 <- THE WALKING DEAD (2003), VOLUME 23: WHISPERS INTO SCREAMS
            e.g. 2003 <- THE WALKING DEAD (2003), VOLUME 13: TOO FAR GONE
            e.g. 2003 <- THE WALKING DEAD (2003), VOLUME 24: LIFE AND DEATH
            e.g. 2017 EDITION <- GUIDE TO EXPLORATION (2017 EDITION)

   4,973 (  4.4%)  Bonus Content
            e.g. WITH BONUS CONTENT <- HOUNDED (WITH BONUS CONTENT): IRON DRUID CHRONICLES, BOOK 1
            e.g. WITH A NEW PREFACE <- ALL MARKETERS ARE LIARS (WITH A NEW PREFACE): THE UNDERGROUN
            e.g. COMPLETELY REVISED AND UPDATED WITH A NEW INTRODUCTION <- ANATOMY OF LOVE: A NATURAL HISTORY OF MATING, MARRIAGE, AND
            e.g. "BRIMMING WITH HOPE" <- KIBO ("BRIMMING WITH HOPE"): RECIPES AND STORIES FROM JAPAN'
            e.g. WITH BONUS CONTENT <- COURAGE TO SOAR (WITH BONUS CONTENT): A BODY IN MOTION, A LI

   2,692 (  2.4%)  Award/Prize
            e.g. NATIONAL BOOK AWARD FINALIST <- THE LEAVERS (NATIONAL BOOK AWARD FINALIST): A NOVEL
            e.g. CHINA 'S FIRST INTERNATIONAL NOMINATION OF ANDERSEN PRIZE LA <- 胖小猪的春天（FAT PIG'S SPRING(CHINA 'S FIRST INTERNATIONAL NOMINAT
            e.g. NATIONAL BOOK AWARD FINALIST <- THE LEAVERS (NATIONAL BOOK AWARD FINALIST): A NOVEL
            e.g. BOOKER PRIZE WINNER <- SHUGGIE BAIN: A NOVEL (BOOKER PRIZE WINNER)
            e.g. PULITZER PRIZE WINNER <- THE RETURN (PULITZER PRIZE WINNER): FATHERS, SONS AND THE LA

   1,153 (  1.0%)  Audio Details
            e.g. UNABRIDGED <- COMING BACK STRONGER: UNLEASHING THE HIDDEN POWER OF ADVERSI
            e.g. UNABRIDGED <- FOLLOW ME: A CALL TO DIE. A CALL TO LIVE. (UNABRIDGED)
            e.g. EDITED AND ABRIDGED <- THE DECLINE AND FALL OF THE ROMAN EMPIRE (EDITED AND ABRIDGE
            e.g. WITH AUDIO RECORDING <- THE POPCORN ASTRONAUTS: AND OTHER BITEABLE RHYMES (WITH AUDI
            e.g. UNABRIDGED <- BEHIND THE CANDELABRA: MY LIFE WITH LIBERACE (UNABRIDGED)

     692 (  0.6%)  Book Club
            e.g. OPRAH'S BOOK CLUB <- THE UNDERGROUND RAILROAD (OPRAH'S BOOK CLUB): A NOVEL
            e.g. OPRAH'S BOOK CLUB <- A TALE OF TWO CITIES AND GREAT EXPECTATIONS (OPRAH'S BOOK CL
            e.g. WITH BONUS INTERVIEW "POST-TRAUMATIC GROWTH AND BUILDING RES <- HBR'S 10 MUST READS ON MENTAL TOUGHNESS (WITH BONUS INTERVIE
            e.g. OPRAH'S BOOK CLUB <- AN AMERICAN MARRIAGE (OPRAH'S BOOK CLUB): A NOVEL
            e.g. OPRAH'S BOOK CLUB <- AN AMERICAN MARRIAGE (OPRAH'S BOOK CLUB): A NOVEL

     466 (  0.4%)  Translation
            e.g. ADAPTED FOR YOUNG ADULTS <- THINGS THAT MAKE WHITE PEOPLE UNCOMFORTABLE (ADAPTED FOR YOU
            e.g. ADAPTED FOR YOUNG PEOPLE <- MOUNTAINS BEYOND MOUNTAINS (ADAPTED FOR YOUNG PEOPLE): THE Q
            e.g. ADAPTED FOR YOUNG READERS <- THE SUM OF US (ADAPTED FOR YOUNG READERS): HOW RACISM HURTS
            e.g. ADAPTED FOR YOUNG READERS <- IT'S TREVOR NOAH: BORN A CRIME: STORIES FROM A SOUTH AFRICAN
            e.g. ADAPTED FOR YOUNG READERS <- THE WOMAN'S HOUR (ADAPTED FOR YOUNG READERS): OUR FIGHT FOR

     226 (  0.2%)  Illustration Info
            e.g. REILLUSTRATED <- IN A DARK, DARK ROOM AND OTHER SCARY STORIES (REILLUSTRATED)
            e.g. REILLUSTRATED <- IN A DARK, DARK ROOM AND OTHER SCARY STORIES (REILLUSTRATED)
            e.g. 150+ SYMBOLS, ILLUSTRATED AND FULLY EXPLAINED <- HOW DREAMS SPEAK: AN INTERACTIVE JOURNEY INTO YOUR SUBCONSCI
            e.g. 150+ SYMBOLS, ILLUSTRATED AND FULLY EXPLAINED <- HOW DREAMS SPEAK: AN INTERACTIVE JOURNEY INTO YOUR SUBCONSCI
            e.g. ILLUSTRATED <- LIFE OF PI (ILLUSTRATED): DELUXE ILLUSTRATED EDITION

### not worth removing all content within ().  ~80% of parentheses content within ebook titles are actually parts of the title